labels = {
 'EN': ['Alarm Clock',
       'Backpack',
       'Batteries',
       'Bed',
       'Bike',
       'Bottle',
       'Bucket',
       'Calculator',
       'Calendar',
       'Candles',
       'Chair',
       'Clipboards',
       'Computer',
       'Couch',
       'Curtains',
       'Desk Lamp',
       'Drill',
       'Eraser',
       'Exit Sign',
       'Fan',
       'File Cabinet',
       'Flipflops',
       'Flowers',
       'Folder',
       'Fork',
       'Glasses',
       'Hammer',
       'Helmet',
       'Kettle',
       'Keyboard',
       'Knives',
       'Lamp Shade',
       'Laptop',
       'Marker',
       'Monitor',
       'Mop',
       'Mouse',
       'Mug',
       'Notebook',
       'Oven',
       'Pan',
       'Paper Clip',
       'Pen',
       'Pencil',
       'Postit Notes',
       'Printer',
       'Push Pin',
       'Radio',
       'Refrigerator',
       'Ruler',
       'Scissors',
       'Screwdriver',
       'Shelf',
       'Sink',
       'Sneakers',
       'Soda',
       'Speaker',
       'Spoon',
       'TV',
       'Table',
       'Telephone',
       'ToothBrush',
       'Toys',
       'Trash Can',
       'Webcam'],
 'IT': ['Sveglia',
        'Zaino',
        'batterie',
        'Letto',
        'Bicicletta',
        'Bottiglia',
        'Secchio',
        'Calcolatrice',
        'Calendario',
        'Candele',
        'Sedia',
        'appunti',
        'Computer',
        'Divano',
        'Le tende',
        'Lampada da scrivania',
        'Trapano',
        'Gomma per cancellare',
        'Segnale d\'uscita',
        'Fan',
        'Schedario',
        'Infradito',
        'Fiori',
        'Cartella',
        'Forchetta',
        'Bicchieri',
        'Martello',
        'Casco',
        'Bollitore',
        'Tastiera',
        'Coltelli',
        'Paralume',
        'Il computer portatile',
        'Marker',
        'Tenere sotto controllo',
        'Mocio',
        'Topo',
        'Tazza',
        'Taccuino',
        'Forno',
        'Pan',
        'Graffetta per fogli',
        'Penna',
        'Matita',
        'Appunti su post-it',
        'Stampante',
        'Puntina da disegno',
        'Radio',
        'Frigorifero',
        'Righello',
        'Forbici',
        'Cacciavite',
        'Mensola',
        'Lavello',
        'Scarpe da ginnastica',
        'Bibita',
        'Speaker',
        'Cucchiaio',
        'TV',
        'Tavolo',
        'Telefono',
        'Spazzolino',
        'Giocattoli',
        'Cestino',
        'Webcam']
}
